; % clisp -i guess_my_number.lisp
; % [1] > (start-over)
(defun guess-my-number()
    (ash (+ *small* *big*) -1))
(defun smaller()
    (setf *big* (1- (guess-my-number)))
    (guess-my-number))
(defun bigger()
    (setf *small* (1+ (guess-my-number)))
    (guess-my-number))
(defun start-over()
    (defparameter *small* 1)
    (defparameter *big* 100)
    (guess-my-number))